[package]
name = "wf-core"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
aes.workspace = true
aes-gcm.workspace = true
cbc.workspace = true
chrono.workspace = true
derive_more.workspace = true
dirs.workspace = true
log.workspace = true
rand.workspace = true
regex = "1.12.3"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
sha2.workspace = true
sysinfo.workspace = true
thiserror.workspace = true
tokio.workspace = true
wf-inventory = { path = "../wf-inventory" }

[features]
default = []
memory = ["dep:memchr", "dep:scopeguard"]

[dependencies.memchr]
workspace = true
optional = true

[dependencies.scopeguard]
workspace = true
optional = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }
